### ISSUE TITLE
[BE] 비드 충전하기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#101]
## Description

- 비드를 충전합니다.

## Tasks

- [x] 비드 이력 db 데이터 입력
- [x] 사용자의 보유 비드, 사용 가능 비드 db 갱신
- [x] 화면에 비드 이력 갱신
- [x] api 명세서 갱신
