### ISSUE TITLE
[BE] 비드 현금화하기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#102]
## Description

- 비드 현금화 합니다.

## Tasks

- [x] db에 비드 현금화로 이력 저장
- [x] 사용자의 보유 비드, 사용 가능 비드에서 마이너스 하기
- [x] api 명세서 갱신
