### ISSUE TITLE
[BE] 비드 이력 보기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#104]
## Description

- 비드 이력 보기 기능을 추가합니다. 

## Tasks

- [x] 전체 비드 이력을 불러오기
- [x] 정렬 조건에 맞게 비드 이력을 불러오기
- [x] 선택된 날짜에 맞게 비드 이력 불러오기
- [x] 상품명 클릭 시 상품 상세 페이지로 이동하도록 수정
- [x] api 명세서 갱신
- [x] 충전, 현금화한 후 비드 이력 갱신되는지 확인하기
