### ISSUE TITLE
[BE] 배송 번호 입력하기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#105]
## Description

- 택배사와 배송 번호를 테이블에 저장합니다.

## Tasks

- [x] 출품 - 낙찰인 상태일 때만 버튼 보이도록 수정
- [x] 택배사와 배송 번호를 테이블에 저장
- [x] 이미 입력했을 경우에는 입력했다고 알림
- [x] api 명세서 갱신
