### ISSUE TITLE
[BE] 마스터컬렉터즈레어 상품 보기

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#117]
## Description

- 마스터컬렉터즈레어 등급 상품에서 고가 순 top 10을 불러와 홈 페이지에 표시합니다.

## Tasks

- [x] 마스터컬렉터즈레어 등급 상품에서 고가 순 top 10을 불러옵니다
- [x] 로그인했을 경우에는 관심 상품 표시하도록 합니다
- [x] api 명세서 갱신
