### ISSUE TITLE
[BE] Item 도메인 엔티티 수정

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Duction2#118]
## Description

- Item 도메인 엔티티 수정

## Tasks

- [x]  FavoriteItem 엔티티 수정
- [x]  Item 엔티티 수정
- [x]  ItemImage 엔티티 수정
- [x] RareRating 엔티티 수정
- [x] UserLog 엔티티 수정
- [x] UserItemKey 복합키 생성
