### ISSUE TITLE
[BE] User 도메인 엔티티 수정

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Duction2#120]
## Description

- User 도메인 엔티티 수정

## Tasks

- [x]  User 엔티티 수정
- [x]  IsActive ENUM 생성
- [x]  Role ENUM 생성
