### ISSUE TITLE
[BE] 커뮤니티 도메인 엔티티 수정

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Duction2#124]
## Description

- 커뮤니티 도메인 엔티티 수정 

## Tasks

- [x]  Community 엔티티 수정
- [x]  FavoriteCommunity 엔티티 수정
- [x]  FavoriteCommunityId 복합키 수정
