### ISSUE TITLE
[FE] 홈 페이지 추가

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#13]
## Description

- 메인 페이지를 추가합니다.

## Tasks

- [x]  메인 이미지 추가
- [x] 타이틀 3개
- [x] 커뮤니티 (아이콘라벨) 10개 표시되도록 함
- [x] 마감 임막 상품 5개
- [x] 최고등급 상품 10개 (2줄)

**Comment by jooYeonIya** [comment]
메인 페이지를 홈 페이지로 이름 변경 
(main.jsx가 있어서 혼동 방지를 위해)
