### ISSUE TITLE
[BE] bidhistory, exhibithistory 엔티티 수정

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Duction2#130]
## Description

- bidhistory, exhibithistory 엔티티 수정

## Tasks

- [x]  출품 이력에 STATUS 추가
- [x]  비드 이력에 연관 관계 추가
- [x]  비드 이력의 bid_id를 bidhistory_id로 수정
