### ISSUE TITLE
[BE] 검수 승낙-배송 번호 입력

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#145]
## Description

- 어떤 작업을 진행할지 간단하게 내용 작성해주세요.

## Tasks

- [x] 송장번호 기입 후, 해당 상품의 상태를 “경매 완료”로 변경 & 검수 완료 번환
- [x] 낙찰자의 보유 비드를 보유 비드 - 낙찰 비드로 업데이트
- [x] 출품자의 보유 비드를 보유 비드 + 낙찰 비드로 업데이트
- [x] 배송 번호 삽입
- [x] api 명세서 갱신
