### ISSUE TITLE
[FE] 출품 상품 목록 보기

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#16]
## Description

- 출품 상품 목록 보기 페이지를 추가합니다.

## Tasks

- [x] 아이템 카드 컴포넌트 클릭 이벤트로 화면 이동 추가
- [x] 받아 올 데이터 커뮤니티id 추가
- [x] 타이틀 추가
- [x] 흐르는 전광판 추가
- [x] 정렬 버튼 3개 추가
- [x] 출품하기 버튼 추가
- [x] 아이템 카드 추가
- [x] 검색 텍스트 필드 추가 
- [x] 파일 이름 변경 -> view 어쩌고
