### ISSUE TITLE
[FE] 출품 상품 등록 페이지 구현

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Duction2#18]
## Description

- DT-01-02-01 출품 상품 등록 페이지 구현

## Tasks

- [x]  상품 이름 텍스트 입력 폼 구현
- [x]  사진 입력 버튼 구현
- [x]  상세 설명 작성 폼 구현
- [x] 상품 상태 입력 라디오 버튼 구현
- [x] 레어 점수 평가 별점 버튼 구현
- [x] 시작가 입력 폼 구현
- [x] 경매 종료일 캘린더 라이브러리 구현
- [x] 즉시 낙찰가 입력 폼 구현
- [x] 취소, 확인 버튼 및 navigate 구현
