### ISSUE TITLE
[FE] 통합 검색 결과 페이지 추가 

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#20]
## Description

- 통합 검색 결과 페이지 추가합니다.

## Tasks

- [x] 타이틀 추가
- [x] 커뮤니티 추가 부분 추가 -> 컴포넌트로 사용 가능
- [ ] _커뮤니티 더보기 버튼 추가_
- [x] 출품 상품 부분 추가
- [ ] _출품 상품 더보기 버튼 추가_
- [x] 홈 페이지에서 검색 했을 때 이 페이지로 넘어오도록 함
- [x] 카테고리를 커뮤니티로 수정
- [x] 카테고리, 출품 상품 탭 추가

**Comment by jooYeonIya** [comment]
더보기 에서 탭 기반 무한 스크롤 방식으로 화면 설계 변경 됨
