### ISSUE TITLE
[FE] 출품 상품 상세 보기 페이지 구현

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Duction2#32]
## Description

- DT-01-02-02 출품 상품 상세 보기 페이지 구

## Tasks

- [x]  마운트 시 상품 DTO 데이터 받아오기 (GET)
- [x]  커뮤니티 명 띄우기
- [x]  상품 사진 띄우기 
- [x]  상품명  띄우기
- [x] 시작가, 현재 입찰가, 즉시 낙찰가 띄우기
- [x] 입찰 버튼 구현 (모달 띄우기)
- [x] 즉시 낙찰 버튼 구현 (Alert 띄우기, POST)
- [x] 남은 시간 줄어들기로 띄우기
- [x] 조회수, 입찰 건수, 상태, 레어 등급, 레어 점수 평가 구현 (POST)
- [x] 신고하기 버튼 구현 (PATCH)
- [x] 입찰 포기 버튼 구현 (Alert 띄우기, PATCH)
- [x] 상세 설명 띄우기
- [x] 출품자 정보 띄우기
