### ISSUE TITLE
[FE] 마이페이지 추가

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#34]
## Description

- 마이페이지를 추가합니다.

## Tasks

- [x] 타이틀 추가
- [x] 프로필 이미지 컴포넌트 추가
- [x] 내 정보 섹션 추가 - 프로필 이미지 컴포넌트, 닉네임, 이메일, 버튼
- [x] 점수/보유비드/사용가능비드 섹션 추가
- [x] 입찰 이력, 출품 이력 컴포넌트 추가
- [x] 관심상품 카드 추가
- [x] 화면 이동 링크 추가
