### ISSUE TITLE
[FE] 비드 이력 페이지 추가

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#44]
## Description

- 비드 이력 페이지 추가합니다. 

## Tasks

- [x]  타이틀 추가
- [x] 비드이력 컴포넌트 추가
- [x] 버튼 2개 추가
- [x] 정렬 옵션 버튼 3개 추가
- [x] 달력 컴포넌트 추가
- [x] 이력 부분 추가
