### ISSUE TITLE
[FE] 전체 css 수정

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#54]
## Description

- 전체 css를 수정합니다.

## Task

- [x] IconPlusLabel 아이콘과 라벨 비율 맞추기 
- [x] 로고용 IconPlusLabel 컴포넌트 만들기
- [x] 헤더 덕션 로고 이미지와 폰트 결정하기 
- [x] 풋터 덕션 로고 이미지 결정하기
- [x] 풋터 화면 아래에 고정
- [x] 커뮤니티 아이콘 (네모 4개) 변경 (된다면 마이페지도)
- [x] 헤더 여백 조정
- [x] 풋터 아래 여백 조정
- [x] 메인 여백 수정
- [x] 메인 이미지 변경
- [x] 검색 텍스트 필드 css 변경
- [x] 사각 버튼 css 변경
- [x] 버튼 위 hover 했을 때 이벤트 css 추가
- [x] 마이 페이지 - 내 점수, 소유 비드, 사용 가능 비드 텍스트 크기 변경
- [x] 내 정보 수정 페이지 - 사진 삭제 변경 버튼 css 변경
- [x] 내 정보 수정 페이지 - 여백 변경 
- [x] 입찰 이력, 출품 이력, 비드 이력 css 변경 
- [x] postForm css 변경 - 커뮤니티 개설 요청, 출품 상품 삭제 요청
- [x] 출품 상품 등록 페이지 css 변경
- [x] 출품 상품 수정 페이지 css 변경
- [x] 텍스트에리어 폰트 크기 사이즈 체크하기 (뭔가 이상함)
- [x] 출품 상품 상세 보기 페이지 css 변경
- [x] 출품 상품 목록 보기 페이지 css 변경
- [x] 통합 검색 결과 페이지 css 변경
- [x] 운영자 페이지 css 변경
- [x] 운영자 상세 페이지 css 변경
- [x] 모달들 css 변경
