### ISSUE TITLE
[FE] 1차 버그 테스트

### ISSUE THREAD

**Issue by jooYeonIya** [bbman9900/Duction2#58]
## Description

- 버그를 찾아서 기입합니다. 

## Tasks

- [x] 메인 화면 - 인기 카테고리 - 카테고리 클릭 - 출품 상품 목록 보기 페이지로 이동 안 함
- [x] 출품 상품 카드 눌렀을 때 상세 보기 화면으로 이동 안 함
- [x] 출품 상품 수정 (등록 페이지도 같을 듯) 페이지에서 취소 누르면 커뮤니티 개설 페이지로 이동되는 점을 전 화면으로 이동시키도록 변경
