### ISSUE TITLE
[BE] 스프링 백엔드 초기 설정

### ISSUE THREAD

**Issue by bbman9900** [bbman9900/Duction2#59]
## Description

- 스프링 백엔드 초기 설정

## Tasks

- [x] 도메인 구입 (ducktion.shop) 
- [x] 개발 환경 통일 (스프링부트 의존성 설치)
- [x]  프로젝트 구조 설정
- [x]  엔티티 구현
- [x] Docker로 MySQL DB 연동
- [x] Item 테이블의 condition 속성이 SQL 예약어라서 DB name은 item_condition 으로 변경
