### ISSUE TITLE
[FE] 커뮤니티 개설 요청 페이지 개발 언어 변경

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#6]
## Description

- 타입스크립트로 작성된 커뮤니티 개설 요청 페이지를 자바스크립트로 변경
- 상의 없이 추가된 디펜던시 삭제

## Tasks

- [x] 확장자를 tsx에서 jsx로 변경
- [x] 타입스크립트 관련된 디펜던시 삭제
- [x] helmet 디펜던시 삭제

**Comment by jooYeonIya** [comment]
위 이슈는 2번 브랜치에서 진행됨
(나머지 수정 사항은 1번 브랜치에서 수정 후 병합)
