### ISSUE TITLE
[BE] 커뮤니티 목록 가져오기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#61]
## Description

- 커뮤니티 목록을 불러와 화면에 표시합니다

## Tasks

- [x] 목록 불러오기 - 초성 별로 불러오기
- [x] 관심 커뮤니티 목록 불러오기
- [x] 로그인 안 한 상태에서는 로그인해주세요 표시하기
- [x] 관심 등록한 내용 표시
- [x] 초성별로 화면에 보여주기
