### ISSUE TITLE
[BE] 인기 커뮤니티

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#62]
## Description

- 인기 커뮤니티 목록을 불러와서 홈 페이지 화면에 표시합니다.

## Tasks

- [x] 커뮤니티의 총 조회수 top 10 커뮤니티 정보를 불러오기
- [x] userId가 있을 경우(로그인했을 경우) 관심 표시가 되어있는지도 불러오기
- [x] 프론트단이랑 연결해서 표시하기
- [x] API 명세서 갱신
