### ISSUE TITLE
[BE] 커뮤니티 관심 등록

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#63]
## Description

- 커뮤니티 관심 등록합니다.

## Tasks

- [x] 프론트엔드에서 커뮤니티 관심 버튼을 눌렀을 때 api 호출 - 홈 페이지, 커뮤니티 목록 페이지 2곳에서
- [x] 백엔드에서 db에 저장
- [x] api 명세서 갱신
