### ISSUE TITLE
[BE] 출품 이력 보기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#66]
## Description

- 출품 이력을 불러와 화면에 표시합니다.

## Tasks

- [x] 날짜, 정렬 타입에 맞춰 목록 불러오기
- [x] 화면에 표시하기
- [x] 표시할 내용이 없을 경우 이력이 없습니다 표시하기
- [x] api 명세서 갱신
