### ISSUE TITLE
[BE] 입찰 이력, 출품 이력 횟수 보기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#68]
## Description

- 입찰 이력, 출품 이력을 불러와서 마이 페이지에 표시합니다.

## Tasks

- [x] 입찰 이력 횟수 불러오기
- [x] 출품 이력 횟수 불러오기
- [x] 기본값은 0으로 설정
- [x] api 명세서 갱신
