### ISSUE TITLE
[BE] 출품 상품 상세 보기 API 구현

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#73]
## Description

- 출품 상품 상세 보기 API 구현

## Tasks

- [x]  출품 상품 상세 보기 API 구현
- [x]  ViewItemDetailsDTO 구현
- [x]  RareTierConverter Utils 구현
- [x]  ItemConditionConverter Utils 구현
- [x]  FE 연동 확인 및 코드 수정
