### ISSUE TITLE
[BE] 마감 임박 상품

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#77]
## Description

- 당일 마감 예정 상품 중 총 조회수 top 5를 불러와 화면에 표시합니다.

## Tasks

- [x] 당일 마감 예정 상품 중 총 조회수 top 5의 목록을 불러오기
- [x] userId가 있을 경우(로그인 했을 경우) 관심 등록되어 있는지 확인하기
- [x] api 명세서 갱신하기
