### ISSUE TITLE
[BE] 입찰 이력 보기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#79]
## Description

- 입찰 이력을 불러와 화며에 표시합니다.

## Tasks

- [x] 정렬, 날짜에 맞게 입찰 이력을 불러오기
- [x] 화면에 표시
- [x] 이력이 없을 경우 이력이 없습니다 표시
- [x] api 명세서 갱신
