### ISSUE TITLE
[BE] 회원 탈퇴하기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#86]
## Description

- 회원 탈퇴 처리를 합니다.

## Tasks

- [x] 출품중, 입찰중, 낙찰중인 경우에는 탈퇴 불가 (상품에 대해 거래가 진행중인 상태에서는 탈퇴 불가)
- [x] 회원 탈퇴 시 플래그를 INACTIVE로 변경 후 탈퇴 처리
- [x] api 명세서 갱신
