### ISSUE TITLE
[BE] 사용자 정보 보기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#87]
## Description

- 사용자 정보를 불러와 화면에 표시합니다.

## Tasks

- [x] 사용자 정보를 불러오기
- [x] 마이페이지 화면에 표시
- [x] 내 정보 보기 화면으로 넘어갈 때 같이 보내주기
- [x] api 명세서 갱신
