### ISSUE TITLE
[BE] 요청 목록 보기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#89]
## Description

- 요청 목록 불러와서 화면에서 표시합니다.

## Tasks

- [x] 개설 요청 목록을 불러와서 화면에 표시
- [x] 삭제 요청 목록을 불러와서 화면에 표시
- [x] api 명세서 갱신
