### ISSUE TITLE
[FE] 출품 상품 삭제 요청 페이지

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#9]
## Description

- 출품상품 삭제요청 페이지, 커뮤니티개설요청페이지, 포스트폼 컴포넌트, 출품상세 삭제 페이지

## Tasks

- [x] 커뮤니티 개설 요청 페이지의 html 단 컴포넌트화 후 재활용
- [x] html title 태그와 placeholder 태그는 출푸상품 삭제요청에 관한 키워드로 변경
- [x] postform.css 작성 
- [x] postform.jsx에도 GodoTitleLabel 컴포넌트 활용
- [x] 커뮤니티 개설요청페이지, 출품상품 삭제요청 페이지, 출품상품 삭제 페이지 작성시 데이터관련 코드 추가하기

**Comment by glennman1** [comment]
현재 task중, postform css를 마저 다 못했습니다. 
godotitlelabel과 추가로 포스트폼 (게시글 작성폼)이 출품상품 삭제요청 페이지에서 태그가 더 추가되어서 PretitleLabel을 사용했으나 css에서의 과정에서 너무 오래걸릴것같다 판단 및 현재 너무 오래 시간소요가 되어서 이부분은 미처 끝내지 못했습니다
추가로 피그마화면의 비율과 다릅니다 최대한 화면과 비슷하게 노력함. (버튼 색 누락)

**Comment by jooYeonIya** [comment]
#54 에서 수정
