### ISSUE TITLE
[BE] 검수 반려하기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#92]
## Description

- 검수 반려 처리합니다.

## Tasks

- [x] 낙찰 취소 - 사용 가능 비드 갱신 
- [x] 패널티: 출품자 평가 0점으로 업데이트, 3번 적발 시 영구 이용 정지 
- [x] api 명세서 갱신
