### ISSUE TITLE
[BE] 신고 승낙하기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#93]
## Description

- 신고 승낙 처리를 합니다.

## Tasks

- [x] 경매 상태 확인 후, 경매 상태에 따라 로직 작성
- [x] 상품 삭제 후 취소 사유를 출품자에게 메일로 전송
- [x] api 명세서 갱신
