### ISSUE TITLE
[BE] 개설 요청 상세보기

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#95]
## Description

- 개설 요청 목록에서 선택한 요청에 대해 상세 보기 페이지를 만듭니다.

## Tasks

- [x] 제목 클릭 시 화면 이동
- [x] 화면 이동 시, 상세 내용 포함해서 이 동
- [x] api 명세서 갱신

**Comment by jooYeonIya** [comment]
원래는 화면 이동 시에 requestId를 넘겨 한 번 더 데이터베이스에서 상세 내용을 가져오는 걸로 하려고 했는데,
그냥 목록 리스트를 가져올 때 내용까지 다 가져와서, 화면 이동 시 데이터 넘겨주는 걸로 구현
