### ISSUE TITLE
[BE] 개설 요청 승낙

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#97]
## Description

- 커뮤니티 개설 요청 승낙 처리를 합니다.

## Tasks

- [x] 커뮤니티에 데이터 입력 - 초성도 같이 입력
- [x] 커뮤니티 개설 요청 테이블에서 데이터 삭제
- [x] api 명세서 갱신
