### ISSUE TITLE
[BE] 개설 요청 반려

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#98]
## Description

- 커뮤니티 개설 요청 반려 처리합니다.

## Tasks

- [x] 거절 사유를 prompt()를 사용해 입력 받음
- [x] 거절 사유를 포함해서 반려 메일 보내기
- [x] 데이터 베이스에서 삭제하기
- [x] api 명세서 갱신
