### ISSUE TITLE
[BE] 삭제 요청 승낙

### ISSUE THREAD

**Issue by glennman1** [bbman9900/Duction2#99]
## Description

- 상품 삭제 요청 승낙 처리합니다.

## Tasks

- [x] 아이템 테이블에서 삭제
- [x] 삭제 요청 테이블에서 삭제
- [x] api 명세서 갱신
